### ISSUE TITLE
 fileExporter.downloadPDFFromBase64(encoded, "fileName.pdf"); Not Working

### ISSUE THREAD

**Issue by shravanshra1** [aviskarkc10/file-exporter#2]
csvtopdf(){
        const base64json = require('base64json');
        const fileExporter = require('file-exporter');
       let data = {"data":[{name: 'John Smith', address: 'New York'}, {name: 'John Doe', address: 'Mississippi'}]};
        let encoded = base64json.stringify(data, null, 2);
        console.log(encoded);
        fileExporter.downloadPDFFromBase64(encoded, "fileName.pdf");
    }

ReferenceError: atob is not defined
    at Module.l (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/file-exporter/build/lib.js:1:1843)
    at ExcelController.csvtopdf (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/api/controllers/Common/ExcelController.js:49:22)
    at Object.csvtopdf [as common/excel/csvtopdf] (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/api/controllers/Common/ExcelController.js:55:59)
    at /home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/sails/lib/router/bind.js:247:46
    at routeTargetFnWrapper (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/sails/lib/router/bind.js:391:9)
    at Layer.handle [as handle_request] (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/layer.js:95:5)
    at /home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/index.js:335:12)
    at next (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/index.js:275:10)
    at next (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/route.js:127:14)
    at module.exports (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/api/policies/isAuthorized.js:9:10)
    at routeTargetFnWrapper (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/sails/lib/router/bind.js:374:23)
    at Layer.handle [as handle_request] (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/layer.js:95:5)
    at /home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/index.js:335:12)
    at next (/home/shravan/Documents/Smart Food Safe/smartfoodsafe-api-sails-multi-tenant/node_modules/express/lib/router/index.js:275:10)

**Comment by aviskarkc10** [comment]
@shravanshra1 Let me know if it's working for you. I am closing the issue.
